@startuml kino find/choise

title "Поиск/выбор фильма"

start
:Открыть каталог;
:Ввести поисковый запрос;
if (Фильмы найдены?) then (да)
  :Показать список;
  :Выбрать фильм;
  :Показать детали;
else (нет)
  :Показать "ничего не найдено";
endif
stop
@enduml
