@startuml kino buy

title "Покупка билетов в кинотеатр"

autonumber
actor Front as u order 10
participant "App" as app order 20 
participant "Cache" as ch order 21
database "Database" as db order 30
participant "Pay API" as pay order 40
participant "Notification" as sms order 50

u -> app++ : POST /order {item: id, sub: id, user: id, amount: int} \nоплата выбранных билетов
app -> app : Аутентифицирован?
opt "Аутентификация"
    app --> u : Запрос номера телефона
    u -> app : POST /auth {phone: number}
    app -> db++ : Поиск/добавление по номеру
    db --> app : userID
    db--
end


app -> db++ : Create Order, Lock seatId (transaction)
db --> app : orderID, status=new
db--
app -> ch : Invalidate seats
note right : "Удаляем кэш по этому залу \n при следующем обращении наполнится снова"

app -> pay++ : POST /pay/create {user: id, order: orderId}
pay --> app : 200 Ok - payID

alt "Payment system not ready"
    pay --> app : 5xx - System Not Ready
    app -> db++ : Order status=error
    db --> app-- : Ok
    app --> u : 5xx Error - Попробуйте оплатить позже
end

app -> db++ : Save payID in Order (status=pending)
db --> app-- : Ok
pay --> u-- : Платежный виджет
app--

u -> pay : Оплата
pay --> app++ : Webhook: orderId, payID, succesfull
app -> db++ : Order status=paid, QR-code
db --> app-- : Ok
app -> ch : Инвалидация кэша
app -> sms : Отправить ссылку на QR-код
sms --> u : Ссылка на билеты
app --> u : Показать билеты (QR-code) на экране
app--

@enduml
